#!/bin/bash
(set -o igncr) 2>/dev/null && set -o igncr; # Ignore Windows line endings

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
